ElLugarFinal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include # new
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
    path('Dashboard', TemplateView.as_view(template_name='Dashboard.html'), name='Dashboard'), # new
]

cobranza/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include # new
from django.views.generic.base import TemplateView # new
from . import views

urlpatterns = [
    path('add/', views.ruta_crear, name='ruta_add'),
    path('<int:pk>/edit/', views.ruta_modificar, name='ruta_edit'),
    path('listar/', views.Rutas_List_View.as_view(), name='ruta_list'),
    path('visita/add/', views.visita_crear, name='vista_add'),
    path('visita/<int:pk>/edit/', views.visita_modificar, name='vista_edit'),
    path('visita/listar/', views.Visitas_List_View.as_view(), name='vista_list'),
    path('propietario/add/', views.propietario_crear, name='propietario_add'),
    path('propietario/<int:pk>/edit/', views.propietario_modificar, name='propietario_edit'),
    path('propietario/editar', views.editar_propietario, name='propietario_edit'),
    path('propietario/listar/', views.Propietarios_List_View.as_view(), name='propietario_list'),
    path('estado_visita/add/', views.estado_visita_crear, name='estado_visita_add'),
    path('estado_visita/<int:pk>/edit/', views.estado_visita_modificar, name='estado_visita_edit'),
    path('editar_visita/', views.editar_visita, name='estado_visita_edit'),
    path('editar_estado/', views.editar_estado_visita, name='edit_estado'),
    path('estado_visita/listar/', views.Estados_visita_List_View.as_view(), name='estado_visita_list'),
    path('gestionar_visitas/', views.gestionar_visitas, name='gesti_visita'),  # new
    path('modificar/', views.modificar, name='mod'),  # new
    path('editar_ruta', views.editar_ruta, name='rutas_edit'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include # new
from django.views.generic.base import TemplateView # new
from . import views

urlpatterns = [
    path('AddUser', TemplateView.as_view(template_name='users/AddUser.html'), name='AddUser.html'), # new
    path('add/', views.usuario_crear, name='person_add'),
    path('<int:pk>/edit/', views.usuario_modificar, name='person_add'),
    path('listar/', views.Usuarios_List_View.as_view(), name='books'),
    path('gestionar_usuario/', views.gestionar_usuario, name='gesti_usuario'),  # new
    path('modificar_usuario/', views.editar_usuario, name='edit_usuario'),
]

cobranza/models.py
from django.db import models
from users.models import CustomUser


class Propietario(models.Model):
	rut = models.CharField(null=False, max_length=30)
	nombres = models.CharField(null=False, max_length=30)
	ap_paterno = models.CharField(null=False, max_length=30)
	ap_materno = models.CharField(null=False, max_length=30)
	direccion = models.CharField(null=False, max_length=30)
	nro = models.IntegerField(null=False)
	comuna = models.CharField(null=False, max_length=30)
	fono_residencial = models.IntegerField(null=False)
	direccion_correo_electronico = models.CharField(null=False, max_length=30)

class Estado_Visita(models.Model):
	nombres_estado_visita = models.IntegerField(null=False)


# Create your models here.
class Ruta(models.Model):	
	cobrador = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	fecha_Ruta = models.DateTimeField()
	def MostrarRutas():
		return True;

# Create your models here.
class Visita(models.Model):
	Observaciones = models.CharField(null=False, max_length=300)
	cliente = models.ForeignKey(Propietario, on_delete=models.CASCADE)
	estado_visita = models.ForeignKey(Estado_Visita, on_delete=models.CASCADE)
	ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE)
	def MostrarRutas():
		return True;

cobranza/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit



class CrearRuta(forms.ModelForm):
    class Meta:
        model = Ruta
        fields = ('__all__')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Agregar ruta'))


class ModificarRuta(forms.ModelForm):
    class Meta:
        model = Ruta
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Actualizar ruta'))

class CrearVisita(forms.ModelForm):
    class Meta:
        model = Visita
        fields = ('__all__')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Agregar Visita'))


class ModificarVisita(forms.ModelForm):
    class Meta:
        model = Visita
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Actualizar Visita'))

class CrearPropietario(forms.ModelForm):
    class Meta:
        model = Propietario
        fields = ('__all__')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Agregar Propietario'))


class ModificarPropietario(forms.ModelForm):
    class Meta:
        model = Propietario
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Actualizar Propietario'))

class CrearEstado_Visita(forms.ModelForm):
    class Meta:
        model = Estado_Visita
        fields = ('__all__')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Agregar Estado Visita'))


class ModificarEstado_Visita(forms.ModelForm):
    class Meta:
        model = Estado_Visita
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Actualizar Estado Visita'))

cobranza/views.py
from django.shortcuts import render, redirect
from .models import CustomUser
from django.views.generic import CreateView
from django.views.generic import UpdateView
from .forms import *
from .models import *
from . import forms
from django.views import generic

# Create your views here.
def ruta_crear(request):
	if request.method == "POST":
		form = forms.CrearRuta(request.POST)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.CrearRuta()
	return render(request, "cobranza/agregar_ruta.html", {'form': form})

def ruta_modificar(request, pk):
	user = Ruta()
	instance = Ruta.objects.get(pk=pk)
	if request.method == "POST":
		form = forms.ModificarRuta(request.POST, instance = instance)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.ModificarRuta(instance = instance)
	return render(request, "cobranza/modificar_ruta.html", {'form': form})

class Rutas_List_View(generic.ListView):
	model = Ruta

# Create your views here.
def visita_crear(request):
	if request.method == "POST":
		form = forms.CrearVisita(request.POST)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.CrearVisita()
	return render(request, "cobranza/agregar_visita.html", {'form': form})

def visita_modificar(request, pk):
	user = Ruta()
	instance = Visita.objects.get(pk=pk)
	if request.method == "POST":
		form = forms.ModificarVisita(request.POST, instance = instance)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.ModificarVisita(instance = instance)
	return render(request, "cobranza/modificar_visita.html", {'form': form})

def editar_ruta(request):
	ruta = Ruta.objects.all()
	context = {'rutas': ruta}
	return render(request, 'cobranza/editar_ruta.html', context)

def editar_visita(request):
	visita = Visita.objects.all()
	context = {'visitas': visita}
	return render(request, 'cobranza/editar_visita.html', context)

class Visitas_List_View(generic.ListView):
	model = Visita

# Create your views here.
def propietario_crear(request):
	if request.method == "POST":
		form = forms.CrearPropietario(request.POST)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.CrearPropietario()
	return render(request, "cobranza/agregar_propietario.html", {'form': form})

def propietario_modificar(request, pk):
	user = Ruta()
	instance = Propietario.objects.get(pk=pk)
	if request.method == "POST":
		form = forms.ModificarPropietario(request.POST, instance = instance)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.ModificarPropietario(instance = instance)
	return render(request, "cobranza/modificar_propietario.html", {'form': form})

class Propietarios_List_View(generic.ListView):
	model = Propietario

# Create your views here.
def estado_visita_crear(request):
	if request.method == "POST":
		form = forms.CrearEstado_Visita(request.POST)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.CrearEstado_Visita()
	return render(request, "cobranza/agregar_estado_visita.html", {'form': form})

def estado_visita_modificar(request, pk):
	user = Ruta()
	instance = Estado_Visita.objects.get(pk=pk)
	if request.method == "POST":
		form = forms.ModificarEstado_Visita(request.POST, instance = instance)
		if form.is_valid():
			form.save()
			return redirect("http://127.0.0.1:8000/Dashboard")
	form = forms.ModificarEstado_Visita(instance = instance)
	return render(request, "cobranza/modificar_estado_visita.html", {'form': form})
def gestionar_visitas(request):
	user = CustomUser()
	return render(request, 'cobranza/gestionar_visitas.html', {})
def modificar(request):
	user = CustomUser()
	return render(request, 'cobranza/modificar.html', {})

def editar_propietario(request):
	propietario = Propietario.objects.all()
	context = {'propietarios': propietario}
	return render(request, 'cobranza/editar_propietario.html', context)

class Estados_visita_List_View(generic.ListView):
	model = Estado_Visita
def editar_estado_visita(request):
	name = Estado_Visita.objects.all()
	context = {'names': name}
	return render(request, 'cobranza/editar_estado_visita.html', context)

templates/cobranza/agregar_estado_visita.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/agregar_propietario.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/agregar_ruta.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/agregar_visita.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/editar_estado_visita.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}
{% block content %}

    <select id="scripts" name="customer">

    {% if names %}
      {% for name in names %}
          <option>{{ name.pk}}</option>
      {% endfor %}
    {% endif %}</select>

    <button onclick = "Function()"> Ingresar </button>
    <script>
    function Function(){
    var sel = document.getElementById('scripts').value;
    window.open("http://127.0.0.1:8000/cobranza/estado_visita/"+document.getElementById('scripts').value+"/edit/")
          }
</script>
{% endblock %}X

templates/cobranza/editar_propietario.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}
{% block content %}

    <select id="scripts" name="customer">

    {% if propietarios %}
      {% for propietario in propietarios %}
          <option>{{ propietario.pk}}</option>
      {% endfor %}
    {% endif %}</select>

    <button onclick = "Function()"> Ingresar </button>
    <script>
    function Function(){
    var sel = document.getElementById('scripts').value;
    window.open("http://127.0.0.1:8000/cobranza/propietario/"+document.getElementById('scripts').value+"/edit/")
          }
</script>
{% endblock %}X

templates/cobranza/editar_ruta.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}
{% block content %}

    <select id="scripts" name="customer">

    {% if rutas %}
      {% for ruta in rutas %}
          <option>{{ ruta.pk}}</option>
      {% endfor %}
    {% endif %}</select>

    <button onclick = "Function()"> Ingresar </button>
    <script>
    function Function(){
    var sel = document.getElementById('scripts').value;
    window.open("http://127.0.0.1:8000/cobranza/"+document.getElementById('scripts').value+"/edit/")
          }
</script>
{% endblock %}X

templates/cobranza/gestionar_visitas.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static '/assets/css/botones.css' %}" rel="stylesheet" />
      <title>Gestionar Visita</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8"><div style="text-align: center;">
             {% load static %}
            <img src="{% static 'media/logoc.png' %}"  width="200" height="280"/>

                <div class="row">
                    <div class="col-md-10 ml-mr-auto"><div class="col-md-10 ml-md-auto">

                <div class="">
                    <a class="botonA btn btn-block" href="http://127.0.0.1:8000/cobranza/propietario/add/">Agregar propietario</a><br>
                    <a class="botonA btn btn-block" href="http://127.0.0.1:8000/cobranza/visita/add/">Agregar visita</a><br>
                    <a class="botonA btn btn-block" href="http://127.0.0.1:8000/cobranza/add/">Agregar ruta</a><br>
                    <a class="botonA btn btn-block" href="http://127.0.0.1:8000/cobranza/estado_visita/add/">Estado visita</a><br>
                    <a class="botonA btn btn-block" href="http://127.0.0.1:8000/cobranza/modificar/">Modificar</a><br>

                </div>
                    </div>
                </div>

                </div>


        </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/cobranza/modificar_estado_visita.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/modificar_ruta.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/modificar_visita.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/cobranza/propietario_list.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Book List</h1>

    {% if visita_list %}
    <ul>

      {% for visita in visita_list %}
      <li>
        <a href="http://127.0.0.1:8000/cobranza/{{ visita.pk }}/edit">{{ visita.ruta.cobrador }}</a> ({{visita.cliente}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}  
{% endblock %}

templates/cobranza/ruta_list.html
{% extends 'base_forms.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>Book List</h1>

    {% if ruta_list %}
    <ul>

      {% for ruta in ruta_list %}
      <li>
        <a href="http://127.0.0.1:8000/cobranza/{{ ruta.pk }}/edit">{{ ruta.cobrador }}</a> ({{ruta.fecha_Ruta}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}  
{% endblock %}